version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arep-app
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      SERVER_PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/arep_auth
    ports:
      - "443:5000"
    volumes:
      - /home/ec2-user/keystores:/app/keystores:ro

  mongodb:
    image: mongo:7.0
    container_name: arep-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: arep_auth
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
