# In resources/application.properties
# The format used for the keystore. It could be set to JKS in case it is a JKS file
server.ssl.key-store-type=PKCS12
# The path to the keystore containing the certificate
server.ssl.key-store=keystores/ecikeystore.p12
# The password used to generate the certificate
server.ssl.key-store-password=123456
# The alias mapped to the certificate
server.ssl.key-alias=ecikeypair
server.ssl.enabled=true

server.port=${SERVER_PORT:5000}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/arep_auth}
spring.data.mongodb.auto-index-creation=true